name: MLOps CI/CD

on:
  push:
    branches:
      - main

jobs:
  code_quality:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      # Step 3: Install dependencies for code quality checks
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install black flake8

      # Step 4: Run code formatting and linting
      - name: Format and Lint
        run: |
          black models/ model_training.py promote_and_register.py app.py tests/
          
  test_model_training:
    runs-on: ubuntu-latest
    needs: code_quality
    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      # Step 3: Install dependencies for testing
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest

      # Step 4: Run the test cases for model_training.py
      - name: Run model training test
        run: python -m pytest tests/test_model_training.py

  build_and_deploy:
    runs-on: ubuntu-latest
    needs: test_model_training
    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Step 3: Install Docker Compose
      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      # Step 4: Build Docker images
      - name: Build Docker images
        run: docker-compose build

      # Step 5: Deploy the application (Streamlit and MLflow) locally
      - name: Deploy containers
        run: docker-compose up -d

      # Step 6: Install Ngrok (for creating public URLs)
      - name: Install Ngrok
        run: |
          sudo apt-get update
          sudo apt-get install -y unzip
          curl -s https://ngrok-agent.s3.amazonaws.com/ngrok.asc | sudo tee /etc/apt/trusted.gpg.d/ngrok.asc >/dev/null
          echo "deb https://ngrok-agent.s3.amazonaws.com buster main" | sudo tee /etc/apt/sources.list.d/ngrok.list
          sudo apt-get update && sudo apt-get install ngrok

      # Step 7: Start Ngrok and expose MLflow UI
      - name: Expose MLflow UI via Ngrok
        run: ngrok http 5000 &

      # Step 8: Expose Streamlit via Ngrok
      - name: Expose Streamlit via Ngrok
        run: ngrok http 8502 &

      # Step 9: Display Ngrok public URLs
      - name: Get Ngrok URLs
        run: |
          sleep 5
          echo "MLflow UI public URL:"
          curl --silent http://127.0.0.1:4040/api/tunnels | jq '.tunnels[0].public_url'
          echo "Streamlit App public URL:"
          curl --silent http://127.0.0.1:4040/api/tunnels | jq '.tunnels[1].public_url'
